const { GoogleGenerativeAI } = require('@google/generative-ai');
const config = require('../config/config');

class GeminiService {
  constructor() {
    if (!config.geminiApiKey) {
      throw new Error('Gemini API Key is not configured');
    }
    this.genAI = new GoogleGenerativeAI(config.geminiApiKey);
    this.model = this.genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });
  }

  /**
   * Generates a response from the Google Gemini AI model based on the user's message and the provided context.
   * It constructs a prompt that includes system instructions, previous conversation context, and the current user message.
   * 
   * @async
   * @method generateResponse
   * @param {string} message - The current message input from the user.
   * @param {string} context - The formatted conversation history retrieved from the database.
   * @returns {Promise<string>} The text response generated by the Gemini model.
   * @throws {Error} Throws an error if the API call fails.
   */
  async generateResponse(message, context) {
  try {
    const prompt = `
You are FinSage AI, an intelligent financial assistant built exclusively for the FinSage wealth management system.

Your identity is strictly FinSage AI.
You must never reference Google, OpenAI, Gemini, or any other external company, model, or provider.
All responses must appear as if they are generated solely by FinSage AI.

Your role is to help users understand, organize, and improve their financial situation through clear, accurate, and professional guidance.

Response rules:
Use clear section headings followed by a colon
Use plain text only
Do not use markdown symbols
Do not use bullet symbols
Do not use emojis
Do not mention Google or any external AI brand
Refer only to FinSage AI when describing capabilities
Do not repeat the user question
Keep responses concise, neutral, and professional
Avoid numbered lists unless absolutely necessary
Do not include disclaimers about being a language model
Do not explain how you were trained

Content restrictions:
Never mention training sources
Never mention datasets
Never mention AI providers or companies
Never compare FinSage AI with other assistants
Never claim external ownership or affiliation

Focus areas:
Income and expense management
Asset and liability awareness
Financial clarity and decision support
Long-term financial goal improvement

Tone and style:
Professional
Calm
Helpful
Business-ready
User-focused

Context:
${context}

User Question:
${message}

Generate a structured, professional response that strictly follows all rules above.
`;

      const result = await this.model.generateContent(prompt);
      const response = await result.response;
      const text = response.text();
      
      return text;
    } catch (error) {
      console.error('Error generating Gemini response:', error);
      throw new Error('Failed to generate response from AI');
    }
  }
}

module.exports = new GeminiService();
