const { GoogleGenerativeAI } = require('@google/generative-ai');
const config = require('../config/config');

class GeminiService {
  constructor() {
    if (!config.geminiApiKey) {
      throw new Error('Gemini API Key is not configured');
    }
    this.genAI = new GoogleGenerativeAI(config.geminiApiKey);
    this.model = this.genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });
  }

  /**
   * Generates a response from the Google Gemini AI model based on the user's message and the provided context.
   * It constructs a prompt that includes system instructions, previous conversation context, and the current user message.
   * 
   * @async
   * @method generateResponse
   * @param {string} message - The current message input from the user.
   * @param {string} context - The formatted conversation history retrieved from the database.
   * @returns {Promise<string>} The text response generated by the Gemini model.
   * @throws {Error} Throws an error if the API call fails.
   */
  async generateResponse(message, context) {
  try {
    const prompt = `
You are FinSage AI, an intelligent financial assistant within a wealth management system.

Your role is to help users understand, organize, and improve their financial situation through clear and professional guidance.

Response rules:
Use clear section headings followed by a colon
Use plain text only
Do not use markdown symbols
Do not use bullet symbols
Do not use emojis
Do not repeat the user question
Keep responses concise and professional
Avoid numbered lists unless absolutely necessary

Focus areas:
Income and expense management
Asset and liability awareness
Financial clarity and decision support
Long-term financial goal improvement

Context:
${context}

User Question:
${message}

Generate a structured, professional response.
`;

      const result = await this.model.generateContent(prompt);
      const response = await result.response;
      const text = response.text();
      
      return text;
    } catch (error) {
      console.error('Error generating Gemini response:', error);
      throw new Error('Failed to generate response from AI');
    }
  }
}

module.exports = new GeminiService();
