const { GoogleGenerativeAI } = require('@google/generative-ai');
const config = require('../config/config');

class GeminiService {
  constructor() {
    if (!config.geminiApiKey) {
      throw new Error('Gemini API Key is not configured');
    }
    this.genAI = new GoogleGenerativeAI(config.geminiApiKey);
    this.model = this.genAI.getGenerativeModel({ model: 'gemini-2.5-flash' });
  }

  /**
   * Generates a response from the Google Gemini AI model based on the user's message and the provided context.
   * It constructs a prompt that includes system instructions, previous conversation context, and the current user message.
   * 
   * @async
   * @method generateResponse
   * @param {string} message - The current message input from the user.
   * @param {string} context - The formatted conversation history retrieved from the database.
   * @returns {Promise<string>} The text response generated by the Gemini model.
   * @throws {Error} Throws an error if the API call fails.
   */
  async generateResponse(message, context) {
    try {
      // Construct the prompt with context
      const prompt = `
        You are a helpful chatbot assistant.
        
        Context from previous conversations:
        ${context}
        
        User Message: ${message}
        
        Please provide a helpful and relevant response based on the context provided.
      `;

      const result = await this.model.generateContent(prompt);
      const response = await result.response;
      const text = response.text();
      
      return text;
    } catch (error) {
      console.error('Error generating Gemini response:', error);
      throw new Error('Failed to generate response from AI');
    }
  }
}

module.exports = new GeminiService();
